services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: fakeguard
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./Data/pg_vector_data:/var/lib/postgresql/data
